### ISSUE TITLE
Include 2MB of ram and use it as chipmem with 2 extra pins for RAS/CAS

### ISSUE THREAD

**Issue by jcagigal** [niklasekstrom/a314#32]
It could be a good idea to add 2MB and use A314 for keeping the entire chipmem in A314. This could have many advantages like full control of the chipmem contents (autoboot may be possible creating the required structures on chipmem).

Check out this card that swaps expansion memory with on board chipmem:
http://www.boobip.com/hardware/A500_2MB/A500-_chip_RAM_mod

Mobo memory could be used as ranger/slow mem.

It would be even better if a Gary adapter was used so more addresses could be accessed. That way expansions could be mapped to memory, e.g. a window of 4MB of memory for RTG memory.

**Comment by niklasekstrom** [comment]
The A600 version of A314 has 2MB SRAM. Using the /ROE pin which is available on A600 the trapdoor expansion port (but not on A500) the DRAM on the motherboard is disabled, so that all 2MB chip memory is provided by A314.

I don't believe there are currently any plans to add a Gary adapter, but anyone is certainly free and encouraged to do so.
