### ISSUE TITLE
Unreadable Disk reported by "info" tool with WB 3.1 and less

### ISSUE THREAD

**Issue by dcutugno** [niklasekstrom/a314#98]
When using old WB versions the INFO command shouldn't report Unreadable Disk, maybe is related on how ID_DOS_DISK type is reported.
https://github.com/niklasekstrom/a314/blob/v1.2.2/Software/a314fs/a314fs.c#L1208

**Comment by niklasekstrom** [comment]
It is important to note that the disk type that is assigned to the volume, https://github.com/niklasekstrom/a314/blob/v1.2.2/Software/a314fs/a314fs.c#L302, must remain, because the pi command uses that disk type identifier to find out if a directory is on an a314fs volume: https://github.com/niklasekstrom/a314/blob/v1.2.2/Software/picmd/pi.c#L217.

Changing the disk type that is returned by ACTION_INFO/ACTION_DISK_INFO might work fine though.
